---
title: "Power of Pause"
description: "Why taking small breaks are beneficial"
author: "Max De Somma"
date: "11/02/24"
categories:
  - reflection
draft: false
---

This week in my prototyping my future self class we learning about the "power of pause". This involves taking a break from work and pausing the stressors in your life. At Mudd this is hard to wrap your head around. It always feels like you need to be working on something or you are falling behind. I have often had to choose between school or spending time with freinds and on hobbies I'm passionate about. Additionally there it felt as if there was little time to rest if I got sick or wasn't feeling 100%. However I am beginning to learn that sometimes taking a break can actually be more beneficial than the cost of time you lose by that taking that break. These breaks don't need to be long but can simply be calling a loved one or taking a short hike outside. If you try to keep banging your head against a problem set or lab it will often take longer to find the answer. In hindsight this is clear but I always thought that taking a break seemed like a waste of time. Going forward I think I will try to determine when I could use a break and actually take a pause seperating myself completely from the problem and not thinking about it for a while.

